# SPDX-FileCopyrightText: 2026 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{
  description = "Cloud-native OIDC: Kubernetes operator syncing OIDC applications and roles to Zitadel";

  inputs = {
    famedly-engineering-standards.url = "github:famedly/engineering-standards";

    nixpkgs.follows = "famedly-engineering-standards/nixpkgs";
    flake-parts.follows = "famedly-engineering-standards/flake-parts";
  };

  outputs =
    { famedly-engineering-standards, flake-parts, ... }@inputs:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [
        famedly-engineering-standards.flakeModules.default

        ./nix/package.nix
        ./nix/chart.nix
        ./nix/workflows/build.nix
        ./nix/workflows/tests.nix
      ];

      systems = famedly-engineering-standards.lib.famedlySystems;

      perSystem = { config, pkgs, ... }: {
        # This is a Rust project, so default to the Rust devshell.
        devShells.default = config.devShells.rust;

        # Helm is needed to lint, template and package the chart.
        devshells.rust.packages = [ pkgs.kubernetes-helm ];

        famedly.standards = {
          rust.projects."." = { };
          nix.projects."." = { };
        };

        # Hard-wrap markdown prose at 80 columns, like most major Rust
        # projects (and matching rustfmt's comment_width). mdformat
        # runs through the treefmt pre-commit hook, so violations are
        # fixed automatically.
        treefmt = {
          programs.mdformat = {
            enable = true;
            settings.wrap = 80;
          };

          # Refer to the binary by name so that the generated
          # treefmt.toml does not contain nix store paths. The package
          # is put on PATH through the prek wrapper and the devshell.
          settings.formatter.mdformat.command = "mdformat";

          # Helm templates are Go templates, not YAML, and no formatter
          # understands them (the standards' own prettier exclusion
          # only matches charts below a subdirectory). The CRDs are
          # generated byte-for-byte by `cnoidc crd`; reformatting them
          # would make `check-crds` fail.
          settings.global.excludes = [
            "charts/*/templates/*"
            "charts/cnoidc/crds/*.yaml"
          ];
        };

        # Check licensing information (SPDX headers and REUSE.toml)
        # against the REUSE specification, and keep the chart's CRDs in
        # step with the Rust types they are generated from. Both run in
        # CI through the check-pre-commit-hooks workflow.
        prek-pre-commit = {
          package.runtimePkgs = [ pkgs.reuse ];

          workspaces.".".repos = [
            {
              repo = "local";
              hooks = [
                {
                  id = "reuse";
                  name = "reuse";
                  description = "Check licensing info for REUSE compliance";
                  pass_filenames = false;

                  entry = "reuse lint";
                  language = "system";
                }
                {
                  id = "crds-up-to-date";
                  name = "crds-up-to-date";
                  description = "Ensure charts/cnoidc/crds/ matches the CRDs defined in src/crd.rs";
                  pass_filenames = false;
                  files = "^(src/crd\\.rs|charts/cnoidc/crds/.*)$";
                  stages = [ "pre-push" ];

                  entry = "nix run .#check-crds";
                  language = "system";
                }
              ];
            }
          ];
        };
      };
    };
}
